// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApCNT-qYQCAyDtWUX3TfLgp7WJpPuE0BM',
    appId: '1:651093595693:web:45c9223e4368da9cfe4aa4',
    messagingSenderId: '651093595693',
    projectId: 'fir-rpg-57ae6',
    authDomain: 'fir-rpg-57ae6.firebaseapp.com',
    storageBucket: 'fir-rpg-57ae6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDHZblvYKVNTDajL4mjODex-hW9a3iD8k',
    appId: '1:651093595693:android:b806f9ab9737f50cfe4aa4',
    messagingSenderId: '651093595693',
    projectId: 'fir-rpg-57ae6',
    storageBucket: 'fir-rpg-57ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8bRPANrnyG67A5hyguVV_mflZpgqCqM',
    appId: '1:651093595693:ios:c9d360c2a19612d7fe4aa4',
    messagingSenderId: '651093595693',
    projectId: 'fir-rpg-57ae6',
    storageBucket: 'fir-rpg-57ae6.appspot.com',
    iosBundleId: 'com.example.demoRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF8bRPANrnyG67A5hyguVV_mflZpgqCqM',
    appId: '1:651093595693:ios:c9d360c2a19612d7fe4aa4',
    messagingSenderId: '651093595693',
    projectId: 'fir-rpg-57ae6',
    storageBucket: 'fir-rpg-57ae6.appspot.com',
    iosBundleId: 'com.example.demoRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApCNT-qYQCAyDtWUX3TfLgp7WJpPuE0BM',
    appId: '1:651093595693:web:49410743a4835995fe4aa4',
    messagingSenderId: '651093595693',
    projectId: 'fir-rpg-57ae6',
    authDomain: 'fir-rpg-57ae6.firebaseapp.com',
    storageBucket: 'fir-rpg-57ae6.appspot.com',
  );

}