// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3a36qmUOKm5ffZ986qzKiwjTu4KF2Frs',
    appId: '1:473585103382:web:26edb5c153bd937841fb37',
    messagingSenderId: '473585103382',
    projectId: 'fir-rpg-d7a46',
    authDomain: 'fir-rpg-d7a46.firebaseapp.com',
    storageBucket: 'fir-rpg-d7a46.appspot.com',
    measurementId: 'G-FHNGDM2TRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA80z9pp-SvSXozoCyb3Xm_1TF1DnY0y_U',
    appId: '1:473585103382:android:a50bc49d74079b3541fb37',
    messagingSenderId: '473585103382',
    projectId: 'fir-rpg-d7a46',
    storageBucket: 'fir-rpg-d7a46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQXxY93c0F38BrbDY7hNx6NYMGaEYis60',
    appId: '1:473585103382:ios:0dee99e109e5573841fb37',
    messagingSenderId: '473585103382',
    projectId: 'fir-rpg-d7a46',
    storageBucket: 'fir-rpg-d7a46.appspot.com',
    iosBundleId: 'com.example.demoRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQXxY93c0F38BrbDY7hNx6NYMGaEYis60',
    appId: '1:473585103382:ios:0dee99e109e5573841fb37',
    messagingSenderId: '473585103382',
    projectId: 'fir-rpg-d7a46',
    storageBucket: 'fir-rpg-d7a46.appspot.com',
    iosBundleId: 'com.example.demoRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3a36qmUOKm5ffZ986qzKiwjTu4KF2Frs',
    appId: '1:473585103382:web:1188fcb4c716c01741fb37',
    messagingSenderId: '473585103382',
    projectId: 'fir-rpg-d7a46',
    authDomain: 'fir-rpg-d7a46.firebaseapp.com',
    storageBucket: 'fir-rpg-d7a46.appspot.com',
    measurementId: 'G-DS15DQSQ5P',
  );
}
